### ISSUE TITLE
使用源码方式 `gods-pen serve fetch` 执行报错

### ISSUE THREAD

**Issue by hainuo** [ymm-tech/gods-pen#52]
```
maliang gods-pen serve fetch                                      [11:13:51]
fs.js:35
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:35:5
    at req_ (/usr/local/lib/node_modules/gods-pen-cli/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/usr/local/lib/node_modules/gods-pen-cli/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/gods-pen-cli/node_modules/fstream/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
```

**Comment by hainuo** [comment]
找到问题了是因为我的机器 node版本为12.x 导致的    目前降级到 11.15 发现可以正常使用
